# Generated by Django 6.0.5 on 2026-06-06 18:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True)),
                ('country_ru', models.CharField(max_length=100, null=True, unique=True)),
                ('country_ky', models.CharField(max_length=100, null=True, unique=True)),
                ('country_uz', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('name_ru', models.CharField(max_length=30, null=True, unique=True)),
                ('name_ky', models.CharField(max_length=30, null=True, unique=True)),
                ('name_uz', models.CharField(max_length=30, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=32, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('person_image', models.ImageField(upload_to='person_image')),
                ('role', models.CharField(choices=[('Actor', 'Actor'), ('Actress', 'Actress'), ('Director', 'Director'), ('both', 'both')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('title_ky', models.CharField(max_length=100, null=True)),
                ('title_uz', models.CharField(max_length=100, null=True)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KG')),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('subscription_status', models.CharField(choices=[('Free', 'Free'), ('VIP', 'VIP')], default='Free', max_length=5)),
                ('subscription_end', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cartoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('title_ru', models.CharField(max_length=30, null=True)),
                ('title_ky', models.CharField(max_length=30, null=True)),
                ('title_uz', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_ky', models.TextField(blank=True, null=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('cartoon_image', models.ImageField(upload_to='cartoon_image')),
                ('year', models.PositiveIntegerField()),
                ('language', models.CharField(choices=[('Kyrgyz', 'Kyrgyz'), ('Russian', 'Russian'), ('Other', 'Other')], max_length=15)),
                ('duration', models.PositiveIntegerField()),
                ('video', models.FileField(upload_to='film_video')),
                ('trailer_url', models.URLField()),
                ('age_rating', models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], max_length=10)),
                ('access_type', models.CharField(choices=[('Free', 'Free'), ('Subscription', 'Subscription'), ('Rent', 'Rent')], max_length=15)),
                ('is_published', models.BooleanField(default=False)),
                ('views_count', models.PositiveBigIntegerField(default=0)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etno.country')),
                ('genres', models.ManyToManyField(to='etno.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('title_ky', models.CharField(max_length=100, null=True)),
                ('title_uz', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_ky', models.TextField(null=True)),
                ('description_uz', models.TextField(null=True)),
                ('poster_image', models.ImageField(upload_to='poster_image')),
                ('year', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('language', models.CharField(choices=[('Kyrgyz', 'Kyrgyz'), ('Russian', 'Russian'), ('Other', 'Other')], max_length=10)),
                ('video', models.FileField(upload_to='film_video')),
                ('trailer', models.URLField()),
                ('access_type', models.CharField(choices=[('Free', 'Free'), ('Subscription', 'Subscription'), ('Rent', 'Rent')], max_length=15)),
                ('rent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('views_count', models.PositiveBigIntegerField(default=0)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etno.country')),
                ('genres', models.ManyToManyField(to='etno.genre')),
                ('persons', models.ManyToManyField(to='etno.person')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('title_ru', models.CharField(max_length=30, null=True)),
                ('title_ky', models.CharField(max_length=30, null=True)),
                ('title_uz', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_ky', models.TextField(blank=True, null=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='series_images')),
                ('year', models.PositiveIntegerField()),
                ('language', models.CharField(choices=[('Kyrgyz', 'Kyrgyz'), ('Russian', 'Russian'), ('Other', 'Other')], max_length=15)),
                ('trailer_url', models.URLField()),
                ('video', models.FileField(blank=True, null=True, upload_to='series_videos')),
                ('access_type', models.CharField(choices=[('Free', 'Free'), ('Subscription', 'Subscription'), ('Rent', 'Rent')], max_length=15)),
                ('is_published', models.BooleanField(default=False)),
                ('views_count', models.PositiveBigIntegerField(default=0)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etno.country')),
                ('genres', models.ManyToManyField(to='etno.genre')),
                ('persons', models.ManyToManyField(to='etno.person')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_list', to='etno.season')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('cartoon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etno.cartoon')),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etno.film')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etno.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etno.series')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('cartoon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etno.cartoon')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etno.favorite')),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etno.film')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etno.series')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('daily', 'daily'), ('monthly', 'monthly'), ('year', 'year')], max_length=15)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_activ', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
