# Generated by Django 6.0.5 on 2026-05-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='serise',
            new_name='series',
        ),
        migrations.AddField(
            model_name='cartoon',
            name='description_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartoon',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartoon',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartoon',
            name='title_ky',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cartoon',
            name='title_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cartoon',
            name='title_uz',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_ky',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_uz',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='film',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='title_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_ky',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_uz',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='season',
            name='title_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='description_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='title_ky',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='title_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='title_uz',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='video_series',
            field=models.FileField(blank=True, null=True, upload_to='series_video'),
        ),
        migrations.AlterField(
            model_name='cartoon',
            name='language',
            field=models.CharField(choices=[('Kyrgyz', 'Kyrgyz'), ('Russian', 'Russian'), ('Other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='cartoon',
            name='views_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='film',
            name='language',
            field=models.CharField(choices=[('Kyrgyz', 'Kyrgyz'), ('Russian', 'Russian'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='film',
            name='rent_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='views_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='series',
            name='language',
            field=models.CharField(choices=[('Kyrgyz', 'Kyrgyz'), ('Russian', 'Russian'), ('Other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='series',
            name='views_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
