# Generated by Django 6.0.5 on 2026-06-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(related_name='film_genre', to='etno.genre'),
        ),
    ]
