# Generated by Django 6.0.5 on 2026-06-22 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etno', '0003_alter_review_film_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteitem',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_film', to='etno.film'),
        ),
        migrations.AlterField(
            model_name='favoriteitem',
            name='watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_item', to='etno.favorite'),
        ),
    ]
