# Generated by Django 6.0.5 on 2026-06-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etno', '0004_alter_favoriteitem_film_alter_favoriteitem_watchlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartoon',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='favoriteitem',
            options={'ordering': ['-added_date']},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['season_number']},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'series'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_activ',
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
